---
title: "p8015_viz_01"
author: "Yiman Rui"
date: "2026-10-01"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggridges)

library(p8105.datasets)
data("weather_df")
weather_df

```

Basic Scatterplot

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) ## no data

```
```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point()

```
```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point()

# labeling the plot
ggp_temp_scatterplot = 
  weather_df |>
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point()

```
Little bit fancier :)
```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .25) +
  geom_smooth(se = F)
```
```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point(aes(color = name), alpha = .25) + # assign color specific for the point not the smooth or any others in the plot. 
  geom_smooth(se = F)
```
Show faceting

```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .25) +
  facet_grid(.~name)

weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .25) +
  facet_grid(cols = vars(name))
```
Other data
```{r}
weather_df |> 
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  geom_smooth(se = F) +
  facet_grid(cols = vars(name))

weather_df |> 
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point(aes(size = prcp), alpha = .5) +
  geom_smooth(se = F) +
  facet_grid(cols = vars(name))
```

Learning assessment:
```{r}
weather_df |> 
  filter(name == "CentralPark_NY") |> 
  mutate(
    tmax = tmax * (9 / 5) + 32,
    tmin = tmin * (9 / 5) + 32) |> 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point() 
```
Hex shape point
```{r}
weather_df |> 
  ggplot(aes(x = tmax, y = tmin)) + 
  geom_hex()
```
Histogram

```{r}
weather_df |> 
  ggplot(aes(x = tmax)) + 
  geom_histogram()

weather_df |> 
  ggplot(aes(x = tmax, fill = name)) + 
  geom_histogram() + 
  facet_grid(. ~ name)
```

Density
```{r}
weather_df |> 
  ggplot(aes(x = tmax, fill = name)) + 
  geom_density(alpha = .3) # alpha is the clearness of the color  
```

Boxplot
```{r}
weather_df |> 
  ggplot(aes(x = name, y = tmax)) + 
  geom_boxplot()

# Violin
weather_df |> 
  ggplot(aes(x = name, y = tmax, fill = name)) + 
  geom_violin(alpha = 0.3)
```
Ridge plots
```{r}
weather_df |> 
  ggplot(aes(x = tmax, y = name)) + 
  geom_density_ridges() # separate out the plot horizontally
```
## Save some of my plots
```{r}
ggp_weather = 
  weather_df |> 
  ggplot(aes(x = date, y = tmax, color = name)) + 
  geom_point(aes(color = name), alpha = .5) + 
  facet_grid(.~ name)

ggp_weather

ggsave("ggp_weather.pdf", ggp_weather)

```
```{r, fig.width = 12, fig.height= .12}
weather_df |>
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point()
```

